.TH "boy" 3 "Sun Feb 26 2017" "Version IIT2015510" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boy
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <boy\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBattr\fP"
.br
.ti -1c
.RI "int \fBintel\fP"
.br
.ti -1c
.RI "int \fBgirl_req\fP"
.br
.ti -1c
.RI "char \fBname\fP [100]"
.br
.ti -1c
.RI "char \fBtype\fP"
.br
.ti -1c
.RI "int \fBbudget\fP"
.br
.ti -1c
.RI "int \fBis_single\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class to store attributes of each boy namely attractiveness, intelligence, girl requirement, name, type, budget, is single 
.SH "Member Data Documentation"
.PP 
.SS "int boy::attr"
from 0 to 100 
.SS "int boy::budget"
from 0 to 10000 
.SS "int boy::girl_req"
girl attractiveness from 0 to 100 
.SS "int boy::intel"
from 0 to 100 
.SS "int boy::is_single"
1 for single, 0 for not 
.SS "char boy::name[100]"
name 
.SS "char boy::type"
'm' for miser, 'g' for generous, 'G' for geek 

.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
