.TH "couples::coup" 3 "Sun Feb 26 2017" "Version IIT2015510" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
couples::coup
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <couples\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBboy\fP [100]"
.br
.ti -1c
.RI "char \fBgirl\fP [100]"
.br
.ti -1c
.RI "char \fBboy_type\fP"
.br
.ti -1c
.RI "char \fBgirl_type\fP"
.br
.ti -1c
.RI "int \fBbudget\fP"
.br
.ti -1c
.RI "int \fBmaint\fP"
.br
.ti -1c
.RI "int \fBboy_hap\fP"
.br
.ti -1c
.RI "int \fBgirl_hap\fP"
.br
.ti -1c
.RI "int \fBcouple_hap\fP"
.br
.ti -1c
.RI "int \fBcompatibility\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure to store details of each couple formed 
.SH "Member Data Documentation"
.PP 
.SS "char couples::coup::boy[100]"
name of boy 
.SS "int couples::coup::boy_hap"
happiness of boy 
.SS "char couples::coup::boy_type"
geek, generous or miser 
.SS "int couples::coup::budget"
budget of boy 
.SS "int couples::coup::compatibility"
compatibility of couple 
.SS "int couples::coup::couple_hap"
happiness of couple 
.SS "char couples::coup::girl[100]"
name of girl 
.SS "int couples::coup::girl_hap"
happiness of girl 
.SS "char couples::coup::girl_type"
desperate, normal or choosy 
.SS "int couples::coup::maint"
maintenance budget of girl 

.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
