.TH "PPL Assignment Directory Reference" 3 "Sun Feb 26 2017" "Version IIT2015510" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PPL Assignment Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBboy\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcouples\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcouples\&.hpp\fP"
.br
.ti -1c
.RI "file \fBgendata\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgendata\&.hpp\fP"
.br
.ti -1c
.RI "file \fBgift\&.hpp\fP"
.br
.ti -1c
.RI "file \fBgirl\&.hpp\fP"
.br
.ti -1c
.RI "file \fBgivegifts\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgivegifts\&.hpp\fP"
.br
.ti -1c
.RI "file \fBq1\&.cpp\fP"
.br
.ti -1c
.RI "file \fBq2\&.cpp\fP"
.br
.in -1c
