.TH "gift" 3 "Sun Feb 26 2017" "Version IIT2015510" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gift
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gift\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "char \fBtype\fP"
.br
.ti -1c
.RI "int \fBprice\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int \fBlux_rate\fP"
.br
.ti -1c
.RI "int \fBlux_diff\fP"
.br
.ti -1c
.RI "int \fButil_val\fP"
.br
.ti -1c
.RI "int \fButil_class\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class to store gifts and their attributes like id, price, value, type 
.SH "Member Data Documentation"
.PP 
.SS "int gift::id"
gift id 
.SS "int gift::lux_diff"
difficulty in obtaining (only for luxury gifts) 
.SS "int gift::lux_rate"
luxury rate (only for luxury gifts) 
.SS "int gift::price"
price of gift 
.SS "char gift::type"
'e' for essential, 'l' for luxury, 'u' for utility 
.SS "int gift::util_class"
utility class (only for utility gifts) 
.SS "int gift::util_val"
utility value (only for utility gifts) 
.SS "int gift::value"
value of gift 

.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
