.TH "PPL Assignment/q2.cpp" 3 "Sun Feb 26 2017" "Version IIT2015510" "PPL Assignment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PPL Assignment/q2.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'boy\&.hpp'\fP
.br
\fC#include 'girl\&.hpp'\fP
.br
\fC#include 'gift\&.hpp'\fP
.br
\fC#include 'couples\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for PPL Assignment from the source code\&.
